import { type Project, PROJECT_TYPES, TECHNOLOGIES } from './types';

export const projects: Project[] = [
  {
    id: 'shelter',
    name: 'Shelter',
    description:
      'A responsive website for an animal shelter, featuring a burger menu, a random animal card slider, modal windows with detailed animal information, and dynamic pagination adapting to different screen sizes.',
    type: PROJECT_TYPES.WEBSITE,
    date: '01-01-2024',
    technologies: [TECHNOLOGIES.HTML, TECHNOLOGIES.SCSS, TECHNOLOGIES.JS, TECHNOLOGIES.BEM],
    githubUrl: '',
    liveUrl: 'https://rolling-scopes-school.github.io/cherkasovaa-JSFEPRESCHOOL2024Q2/shelter/pages/main/',
    imageUrl: 'shelter.png',
  },
  {
    id: 'nonogram',
    name: 'Nonogram',
    description:
      'A single-page web-based implementation of the classic Japanese Nonograms puzzle game, built with vanilla JavaScript. Features multiple difficulty levels, responsive design, game state saving, dark/light themes, a high score table, and a solution display.',
    type: PROJECT_TYPES.GAME,
    date: '01-11-2024',
    technologies: [TECHNOLOGIES.HTML, TECHNOLOGIES.SCSS, TECHNOLOGIES.JS, TECHNOLOGIES.BEM, TECHNOLOGIES.WEBPACK],
    githubUrl: '',
    liveUrl: 'https://rolling-scopes-school.github.io/cherkasovaa-JSFE2024Q4/nonograms/',
    imageUrl: 'nonograms.png',
  },
  {
    id: 'simon-says',
    name: 'Simon Says',
    description:
      'A classic memory training game. Features multiple difficulty levels, random sequence generation, visual key highlighting, input validation, user feedback, and a sequence replay option.',
    type: PROJECT_TYPES.GAME,
    date: '01-12-2024',
    technologies: [TECHNOLOGIES.HTML, TECHNOLOGIES.SCSS, TECHNOLOGIES.JS],
    githubUrl: '',
    liveUrl: 'https://rolling-scopes-school.github.io/cherkasovaa-JSFE2024Q4/simon-says/',
    imageUrl: 'simon.png',
  },
  {
    id: 'coffee-house',
    name: 'Coffee House',
    description: 'Coffee House is a website for a coffee shop featuring a product catalog.',
    type: PROJECT_TYPES.WEBSITE,
    date: '01-01-2023',
    technologies: [TECHNOLOGIES.HTML, TECHNOLOGIES.SCSS, TECHNOLOGIES.JS],
    githubUrl: 'https://github.com/cherkasovaa/coffee-house',
    liveUrl: 'https://cherkasovaa.github.io/coffee-house/',
    imageUrl: 'coffee-shop.png',
  },
  {
    id: 'async-race-app',
    name: 'Async Race',
    description: "The project simulates a racing competition between cars from the user's collection.",
    type: PROJECT_TYPES.SPA,
    date: '01-04-2025',
    technologies: [TECHNOLOGIES.TS, TECHNOLOGIES.CSS_MODULES, TECHNOLOGIES.WEBPACK, TECHNOLOGIES.FETCH_API],
    githubUrl: 'https://github.com/cherkasovaa/async-race-app',
    liveUrl: 'https://cherkasovaa.github.io/async-race-app/',
    imageUrl: '',
  },
  {
    id: 'decision-making-tool',
    name: 'Decision Making Tool',
    description:
      'Decision Making Tool is a single-page application (SPA) designed to help make weighted random decisions. This tool allows users to create custom option lists with different weights and visualize the selection process with smooth animations.',
    type: PROJECT_TYPES.SPA,
    date: '01-03-2025',
    technologies: [
      TECHNOLOGIES.TS,
      TECHNOLOGIES.CSS_MODULES,
      TECHNOLOGIES.WEBPACK,
      TECHNOLOGIES.CANVAS_API,
      TECHNOLOGIES.FILE_API,
    ],
    githubUrl: 'https://github.com/cherkasovaa/decision-making-tool',
    liveUrl: 'https://cherkasovaa.github.io/decision-making-tool/',
    imageUrl: 'decision-making-tool.png',
  },
  {
    id: 'christmas-shop',
    name: 'Сhristmas Shop',
    description:
      'A festive e-commerce website with a unique Christmas design, featuring a burger menu, an image slider, random gift displays, a New Year countdown timer, gift category switching, a back-to-top button, and modal windows with product details.',
    type: PROJECT_TYPES.WEBSITE,
    date: '01-01-2025',
    technologies: [TECHNOLOGIES.HTML, TECHNOLOGIES.SCSS, TECHNOLOGIES.JS, TECHNOLOGIES.BEM],
    githubUrl: 'https://github.com/cherkasovaa/christmas-shop',
    liveUrl: 'https://cherkasovaa.github.io/christmas-shop/',
    imageUrl: 'christmas-shop.png',
  },
  {
    id: 'portfolio-website-v1',
    name: 'Portfolio',
    description:
      'A modern single-page application (SPA) created with a love for clean code, user experience, and up-to-date technologies.',
    type: PROJECT_TYPES.SPA,
    date: '01-06-2025',
    technologies: [
      TECHNOLOGIES.REACT,
      TECHNOLOGIES.TS,
      TECHNOLOGIES.TAILWIND,
      TECHNOLOGIES.REACT_ROUTER,
      TECHNOLOGIES.VITE,
      TECHNOLOGIES.NETLIFY,
    ],
    githubUrl: 'https://github.com/cherkasovaa/website',
    liveUrl: 'https://cherkasovaa.netlify.app/',
    imageUrl: 'portfolio-website-2025.png',
  },
  {
    id: 'game-shop',
    name: 'Game Shop',
    description:
      'A single-page application (SPA) for an online game store. The project features user authentication, logging, convenient navigation between pages, a product catalog with filtering and sorting options, and much more.',
    type: PROJECT_TYPES.SPA,
    date: '01-05-2025',
    technologies: [
      TECHNOLOGIES.REACT,
      TECHNOLOGIES.TS,
      TECHNOLOGIES.MATERIAL_UI,
      TECHNOLOGIES.REACT_ROUTER,
      TECHNOLOGIES.TANSTACK,
      TECHNOLOGIES.VITE,
    ],
    githubUrl: 'https://github.com/cherkasovaa/e-commerce-application',
    liveUrl: 'https://cherkasovaa.github.io/e-commerce-application/',
    imageUrl: 'e-commerce-tools.png',
  },
  // {
  //   id: '',
  //   name: '',
  //   description: '',
  //   type: '',
  //   date: 2025,
  //   technologies: [],
  //   githubUrl: '',
  //   liveUrl: '',
  //   imageUrl: '',
  // },
];
